### ISSUE TITLE
Congratulations screen appears upon clearing all levels on World 1, even though not all of them were cleared with three stars

### ISSUE THREAD

**Issue by ignishikari** [Grzybojad/Pingo#4]
After I finished my first pass through the levels, the game congratulated me for clearing all levels with three stars - except I actually didn't get three stars on half of them (tbh I just wanted to look at the World 2 levels, so I kinda rushed through World 1 lol). It's a minor bug but thought you might want to know.

**Comment by Grzybojad** [comment]
I've pushed a fix to this issue 14cd8b2c288c0611ca81cd4c1ca44be13bc536d6

Thank you for reporting this issue, I'll upload a new build later.
