### ISSUE TITLE
Vita rebooted while running the game

### ISSUE THREAD

**Issue by ignishikari** [Grzybojad/Pingo#5]
Opened a separate issue for this since it's a different thing

I'm running Enso 3.60 on a fat vita, sd2vita with storagemgr. ur0:tai/config file [here](https://gist.github.com/ignishikari/e6e2e338a40eef841ee035db1ba5d49a). Got the latest version of the game from Vita HBB. I was playing the game last night after leaving it on sleep mode, and while playing my Vita crashed and restarted with no warning. This hasn't happened with any other app or game so far, and I'm unsure of what caused it. I haven't played the game since. Are there any crash logs I should look for that can be attached to this issue? 

Loving the game btw, awesome work!

**Comment by Grzybojad** [comment]
Would you mind elaborating a bit more? You put the Vita into sleep mode, resumed, played for a bit (How long?) and it crashed (Did it freeze? Did you see a crash screen?) ?

If it were an issue with Pingo, it would probably be a memory leak, but I don't know of any leaks right now.

There might be a psp2core crash log in ux0:/data, but if it crashed and restarted without displaying the crash screen, it probably wasn't created.

I don't know what caused the crash, or if it was even Pingo related. At this point, I can't think of a solution.
